export const actionTypes = {
  SEND_INITIAL_POKEAPI_REQUEST_SUCCSESS: 'SEND_INITIAL_POKEAPI_REQUEST_SUCCSESS',
  SEND_INITIAL_POKEAPI_REQUEST_FAIL: 'SEND_INITIAL_POKEAPI_REQUEST_FAIL',

  SEND_INITIAL_INDIVIDUAL_POKEMON_REQUEST_SUCCSESS: 'SEND_INITIAL_INDIVIDUAL_POKEMON_REQUEST_SUCCSESS',
  SEND_INITIAL_INDIVIDUAL_POKEMON_REQUEST_FAIL: 'SEND_INITIAL_INDIVIDUAL_POKEMON_REQUEST_FAIL',

  INDIVIDUAL_REQUESTS_FINISHED: 'INDIVIDUAL_REQUESTS_FINISHED',

  SEND_INDIVIDUAL_POKEMON_REQUEST: 'SEND_INDIVIDUAL_POKEMON_REQUEST',
  CLEAR_SEARCH_LIST: 'CLEAR_SEARCH_LIST',

  REQUEST_POKEMON_DATA: 'REQUEST_POKEMON_DATA',
  RESET_POKEMON_DATA: 'RESET_POKEMON_DATA',
  REQUEST_POKEDEX_DATA: 'REQUEST_POKEDEX_DATA' 
}
