export const actionTypes = {
  HELLO_WORLD: 'HELLO_WORLD',
  SEND_POKEAPI_REQUEST: 'SEND_POKEAPI_REQUEST',
  SEND_POKEAPI_REQUEST_SUCCSESS: 'SEND_POKEAPI_REQUEST_SUCCSESS',
  SEND_POKEAPI_REQUEST_FAIL: 'SEND_POKEAPI_REQUEST_FAIL',
  REQUEST_POKEMON_DATA: 'REQUEST_POKEMON_DATA',
  RESET_POKEMON_DATA: 'RESET_POKEMON_DATA'
}
